name: Build & Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  buildAndTest:
    name: Build & Test
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checkout Airfoil Shared Actions
        uses: actions/checkout@v4
        with:
          repository: airfoil-io/shared-actions
          ref: main
          path: shared-actions

      - name: Setup Airfoil Shared Actions Environment
        uses: ./shared-actions/setup-env

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Gradle Build
        uses: ./shared-actions/gradle-build
        with:
          artifactVersion: ${{ env.PACKAGE_VERSION }}
          user: ${{ secrets.GH_USERNAME }}
          token: ${{ secrets.GH_TOKEN }}
